import type { Metadata } from "next";
import LayoutClientWrapper from "./LayoutClientWrapper";
import { options } from "./api/auth/[...nextauth]/options";
import { getServerSession } from "next-auth";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Truk App",
  description: "Generated by Trukapp team",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);

  return (
    <html lang="en" style={{ height: "100%" }}>
      <body style={{ height: "100%", margin: 0 }}>
        <Providers>
          <LayoutClientWrapper session={session}>
            {children}
          </LayoutClientWrapper>
        </Providers>
      </body>
    </html>
  );
}
